# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-22 16:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Target',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(default='Ellen', max_length=50)),
                ('target_description', models.CharField(max_length=300)),
                ('target', models.PositiveIntegerField(default=0)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('priority', models.SmallIntegerField(default=1, help_text='приоритет в показе')),
            ],
        ),
    ]
