# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-22 16:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='target',
            name='done',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
