# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-08-08 19:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0003_auto_20171022_2328'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='target',
            options={'ordering': ['priority', 'target_description']},
        ),
    ]
