# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-12-06 14:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0005_auto_20180822_1335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='target',
            name='priority',
            field=models.SmallIntegerField(choices=[(1, 'обычный порядок'), (0, 'показывать в начале')], default=1, help_text='приоритет в показе'),
        ),
    ]
