# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-12-07 08:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0006_auto_20181206_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='target',
            name='target',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
